apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-secret
  namespace: fake-news-app
type: Opaque
stringData:
  # Replace with your actual MongoDB Atlas Connection String
  # Format: mongodb+srv://<username>:<password>@cluster.mongodb.net/fake_news_db?retryWrites=true&w=majority
  MONGODB_URI: "mongodb+srv://EshwarSai:Sai792005@cluster0.0bjadl9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
