apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-secret
  namespace: fake-news-app
type: Opaque
stringData:
  # Replace with your actual MongoDB Atlas Connection String
  # Format: mongodb+srv://<username>:<password>@cluster.mongodb.net/fake_news_db?retryWrites=true&w=majority
  #or
  #kubectl create secret generic mongodb-atlas-secret --from-literal=MONGODB_URI="your-real-uri" --namespace=fake-news-app --dry-run=client -o yaml | kubectl apply -f -
  MONGODB_URI: "YOUR_MONGODB_URI_HERE"
